FROM ubuntu:22.04
RUN apt update \
    && apt install -y \
        python3 \
        python3-pip \ 
    && pip install jsonrpcserver jsonrpcclient requests
COPY /scripts/rpc/swarm_server.py swarm_server.py
EXPOSE 65001

CMD ["python3", "swarm_server.py"]