FROM ubuntu:22.04
COPY /scripts/networking/localtime  /etc/localtime
RUN apt update \
    && apt install -y \
        network-manager \
        iptables \
        netcat \
        tcpdump \
        iputils-ping \  
        python3 \
        python3-pip 
RUN pip install --upgrade jsonschema 
COPY networking.py /networking.py
COPY networks.json /networks.json

ENTRYPOINT ["python3", "networking.py", "/networks.json"]