version: "3"
services:
  networking:
    build: 
      context: .
      dockerfile: Dockerfile.networking
    network_mode: "host"
    container_name: networking
    restart: no
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    logging:
      driver: "json-file"  
      options:
        max-size: "10m" 

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.swarm_server
    depends_on:
      - networking
      - drone_1
      - drone_2
    networks:
      swarm:
        ipv4_address: 172.230.220.2
    ports:
      - "65001:65001"
    logging:
      driver: "json-file"  
      options:
        max-size: "10m" 
    
  drone_1:
    container_name: drone_1
    build:
      context: .
      dockerfile: Dockerfile.swarm_node
    depends_on:
      - networking
    networks:
      swarm:
        ipv4_address: 172.230.220.3
    logging:
      driver: "json-file"  
      options:
        max-size: "10m" 

  drone_2:
    container_name: drone_2
    build:
      context: .
      dockerfile: Dockerfile.swarm_node
    depends_on:
      - networking
    networks:
      swarm:
        ipv4_address: 172.230.220.4
    logging:
      driver: "json-file"  
      options:
        max-size: "10m" 

networks:
  swarm:
    driver: bridge
    ipam:
     config:
       - subnet: 172.230.220.0/24
         gateway: 172.230.220.1