FROM ubuntu:22.04
RUN apt update \
    && apt install -y \
        python3=3.10.6-1~22.04 \
        python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    && pip install jsonrpcserver==5.0.9 jsonrpcclient==4.0.3 requests==2.32.2
COPY /scripts/rpc/swarm_server.py swarm_server.py
EXPOSE 65001

CMD ["python3", "swarm_server.py"]