FROM ubuntu:22.04
RUN apt update \
    && apt install -y \
        python3=3.10.6-1~22.04 \
        python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    && pip install jsonrpcserver==5.0.9
COPY /scripts/rpc/server.py server.py
EXPOSE 65000

CMD ["python3", "server.py"]