FROM ubuntu:22.04
RUN apt update \
    && apt install -y \
        python3 \
        python3-pip \ 
    && pip install jsonrpcserver
COPY /scripts/rpc/server.py server.py
EXPOSE 65000

CMD ["python3", "server.py"]