name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v2

    - name: Build and run containers
      run: |
        docker-compose up -d -f ./swarm/docker-compose.yml
        sleep 5
        docker ps

    - name: Check containers status
      run: |
        if docker ps | grep -q "droner"; then
            echo "Containers are running successfully"
        else
            echo "Error occurred while running containers"
            exit 1
        fi
